workflows:
  android-release:
    name: Gerbarij Bezymyannogo - Android Release

    environment:
      java: 17

    scripts:
      - name: Unpack Android project
        script: |
          rm -rf buildsrc
          mkdir buildsrc
          unzip -q *.zip -d buildsrc

      - name: Build APK
        script: |
          PROJECT_DIR="$(dirname "$(find buildsrc -name settings.gradle -type f -print -quit)")"
          cd "$PROJECT_DIR"
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - buildsrc/**/app/build/outputs/apk/release/*.apk
